{{badges}}
[![Crates.io](https://img.shields.io/crates/v/{{crate}})](https://crates.io/crates/{{crate}})
[![Docs.rs](https://img.shields.io/badge/docs.rs-{{crate}}-green)](https://docs.rs/{{crate}})

# {{crate}}

{{readme}}

License: {{license}}

This README was generated by [cargo-readme](https://github.com/livioribeiro/cargo-readme).
