{{badges}}
[![Crates.io](https://img.shields.io/crates/v/{{crate}})](https://img.shields.io/crates/v/{{crate}})
[![Docs.rs](https://docs.rs/{{crate}})](https://docs.rs/{{crate}})

# {{crate}}

{{readme}}

Current version: {{version}}

License: {{license}}

This README was generated by [cargo-readme](https://github.com/livioribeiro/cargo-readme).
